### ISSUE TITLE
`Modeling exercises`: Feedback for Modeling Exercises not visible

### ISSUE THREAD

**Issue by mbmueller** [ls1intum/Artemis#10139]
### Describe the bug

The Boxes are overlapping, therefore the Feedback and Complaints are not visible.

### To Reproduce

Open Modeling Task that has received Feedback with a complaint.

### Expected behavior

Boxes should not overlap

### Screenshots

![image](https://github.com/user-attachments/assets/36d17658-9f12-48d1-b011-9016adf44829)

### Which version of Artemis are you seeing the problem on?

7.8.3

### What browsers are you seeing the problem on?

Chrome

**Comment by krusche** [comment]
We need to reopen this issue, because #10145 led to issues in the modeling assessment detected by e2e tests. We will try to find a different solution

**Comment by Kiara65** [comment]
Got fixed in https://github.com/ls1intum/Artemis/pull/10698

**Comment by ge94zec** [comment]
Although the issue was not reproducible during testing, it still occurs intermittently. We need to reopen this issue, as it continues to cause problems in the modeling assessment in Patterns.

<img width="1484" height="264" alt="Image" src="https://github.com/user-attachments/assets/1bc59593-241d-4d03-a9ba-ab367e366556" />
