### ISSUE TITLE
Edit and delete buttons for the QA area do not work

### ISSUE THREAD

**Issue by rssws** [ls1intum/Artemis#2333]
### Describe the bug
Edit and delete buttons for the QA area do not work. They disappeared somehow. After hiding and showing the QA bar, they both appear. I only tried the edit button, and I can edit the text. But, the submission was failed and the site alerted the "Bad request" error. It worked actually perfect fine today afternoon, but somehow it doesn't work now anymore..

#### To Reproduce

1. Go to 'Exercise', there is no edit/delete button on the QA area, even if the question was submitted by me.
2. Click on the hide 'arrow', then click again to show the sidebar.
3. Two buttons both appear.
4. Click on edit button, change some text
5. Click 'save question' button, see the error "Bad request".

#### Expected behavior

Of course it should be well functioning :)

#### Screenshots

![image](https://user-images.githubusercontent.com/8230635/98030871-f3e3c500-1e11-11eb-9579-3fae0a493933.png)

### Environment

<details><pre>
 - OS: macOS
 - Browser Chrome 
 - Version 86.0.4240.111 (Official Build) (x86_64)
</pre></details>

#### Output in Web Console

<details><pre>
  [REPLACE THIS WITH YOUR INFORMATION]
</pre></details>

**Comment by filip-gregurevic** [comment]
Thank you for the bug report! This should be fixed with https://github.com/ls1intum/Artemis/pull/2322 and the next release 🚀

**Comment by filip-gregurevic** [comment]
@rssws Could you please verify that it works as expected now? Thank you!

**Comment by rssws** [comment]
Sadly, I think the bug is still there.

1. I still have to toggle the sidebar to see both buttons
2. I tried to change the post I submitted before. But this time, the alert is "Internal server error".

![image](https://user-images.githubusercontent.com/8230635/98302512-ce46ef00-1fbc-11eb-9f13-990ba5f82971.png)

**Comment by filip-gregurevic** [comment]
@rssws Thank you the screenshots really helped! This should be fixed with https://github.com/ls1intum/Artemis/pull/2351
CC: @krusche
