### ISSUE TITLE
Result of exercise changes on reload

### ISSUE THREAD

**Issue by reschandreas** [ls1intum/Artemis#556]
### Describe the bug
When clicking on a exercise that's already corrected, the points change when going back to the exercise list. On reload of the website the points change back to the real value. 
#### To Reproduce
1. Go to exercise list
2. Click on an exercise
3. Go back to the exercise
4. Check points

#### Expected behavior
Points should be the same

#### Screenshots
before:
<img width="1103" alt="Screenshot 2019-06-05 at 11 01 40" src="https://user-images.githubusercontent.com/16179620/58944253-b3e26380-8781-11e9-871a-eefd83f95cbd.png">

after:
<img width="1110" alt="Screenshot 2019-06-05 at 11 01 47" src="https://user-images.githubusercontent.com/16179620/58944223-a5944780-8781-11e9-82fc-aa0e62a27b0f.png">

### Environment
<details><pre>
 - OS: macOS
 - Browser: Chrome
 - Version: 74.0.3729.169
</pre></details>

#### Additional context
Doesn't work with every exercise, but with the first one all the time

**Comment by krusche** [comment]
Thanks for reporting. This bug should be fixed in the new release 3.1.5 that will be deployed soon.

**Comment by reschandreas** [comment]
Just checked again and the bug is still there. And in the release notes it says that the current version is already 3.1.6, so maybe some changes made there broke the system again.

**Comment by krusche** [comment]
Could you provide some screenshots and more details when exactly this problem occurs?

**Comment by krusche** [comment]
Please keep in mind, that if you commit and push code, the results automatically changes after around 10-15s (basically when the result of the continuous integration server is available). However, if you do not participate in the exercise, the result should stay the same

**Comment by reschandreas** [comment]
I don't know how I could explain it better, so I recorded a short [video](https://drive.google.com/open?id=1Zl0DYtUPap9dL4xsN2fgm30gE2dHEZXT).
Also this happens only on code exercises and also with very old ones too so nothing I am changing something constantly.

**Comment by krusche** [comment]
Thanks for reporting, we will look into it and fix it! 

By the way: does this also happen in newer exercises?

**Comment by krusche** [comment]
@SiggZ @thilo-behnke I think you have recently worked on this. Can you watch the video and try to fix the issue?

**Comment by thilo-behnke** [comment]
Thank you for the report, I will look into it.

**Comment by thilo-behnke** [comment]
Will be fixed in https://github.com/ls1intum/ArTEMiS/pull/579.

**Comment by krusche** [comment]
Fixed in #580 and shipped with Release 3.2.0
@reschandreas Thanks again for reporting! Please review if it works correctly in the new release tomorrow morning and let us know if you experience any additional problems with the display of results.
