### ISSUE TITLE
Issues with translation not found on programming exercise result page

### ISSUE THREAD

**Issue by Santia-go** [ls1intum/Artemis#6211]
### Describe the bug

From the students perspective, the windows that shows the results of a programming exercise in English shows "Translation-not-found"

### To Reproduce

1. Submit a solution for an automatic homework exercise
2. Wait for the automatic assessment
3. Click on your results
4. See the following window. 
<img width="835" alt="image" src="https://user-images.githubusercontent.com/88991954/217224662-92925b97-52b1-4cc2-8c8d-529756841702.png">

### Expected behavior

This window should be corrected translated

### Which version of Artemis are you seeing the problem on?

6.0.2

### What browsers are you seeing the problem on?

Chrome

**Comment by JohannesStoehr** [comment]
This is probably an issue with old cached data. Clearing the browser cache and reloading the site should fix this "bug"

**Comment by thomasw04** [comment]
Not sure if it is only related to old cached data. I have the same issue, although i deleted all the cached data and tried it on Chrome, Firefox and Edge. Still, the issue persists everywhere. Furthermore my system language is set to only German.

**Comment by JohannesStoehr** [comment]
@thomasw04 Do you see any interesting things in the network tab of a browser of your choice?
There should be a request for en.json/de.json that loads all those translations.
Another interesting thing would be if you also have that problem when you switch the language on the top right of Artemis

**Comment by thomasw04** [comment]
Yes, it tries to load en.json and de.json. But it errors with "(failed) net::ERROR_CONTENT_LENGTH_MISMATCH".
Also, when I try to switch languages, it tries to fetch en.json + de.json (it loads about 30 seconds) and then it fails with a CORS error.

**Comment by thomasw04** [comment]
Are there any news on this @JohannesStoehr?

**Comment by frtakbb47** [comment]
Unable to reproduce the issue, it is outdated and no longer relevant.
