### ISSUE TITLE
Quiz results are still not saved

### ISSUE THREAD

**Issue by just-max** [ls1intum/Artemis#8694]
### Describe the bug

Like in https://github.com/ls1intum/Artemis/issues/8567, quiz results are not being saved.

### To Reproduce

1. Create a quiz with batch mode individual
2. Participate in the quiz
3. Check the scores or participation tab of the quiz.
4. See that there is no result.

### Expected behavior

Quiz participation should be saved

### Screenshots

Before the timer runs out (student view):
![image](https://github.com/ls1intum/Artemis/assets/17551908/2cdc29f4-c04d-453d-988a-23291d352ec3)

After the timer runs out (student view):
![image](https://github.com/ls1intum/Artemis/assets/17551908/84428c0c-8f66-4b5b-958d-66a04025bf3e)

The participation view (empty):
![image](https://github.com/ls1intum/Artemis/assets/17551908/80cacd8f-7e58-4f64-92c8-363c020c4769)

One of our students reported that:
> I submitted my [...] quiz, but it still just shows "currently participating" without any result.

### Which version of Artemis are you seeing the problem on?

7.1.1

### What browsers are you seeing the problem on?

Firefox

**Comment by jerhard** [comment]
This is for a quiz that will be open until the end of the semester, where students can compensate for the points in the other quiz. A fix to this issue should allow to the students that had the problem to successfully participated in the ongoing exercise.

**Comment by FelixTJDietrich** [comment]
Was this issue related to/fixed by #8703?

**Comment by michael-schwarz** [comment]
@krusche: Unfortunately, it seems the issue was not in fact fixed. (Or there is another bug with similar effects?)

For this week's quiz (working time ended today 6pm CEST) in the FPV course (https://artemis.in.tum.de/course-management/351/quiz-exercises/14041) only one student seems to have received a score, even though several hundred students submitted it.

One of our students sent this screenshot of what it looks like for them:
![image](https://github.com/ls1intum/Artemis/assets/13812333/5b9981d4-f639-471c-ad85-c7e91dcc9eb6)

**Comment by michael-schwarz** [comment]
In the participation view, it looks like only the student who has the earliest start date for the quiz got a score, for all others it still shows `participating` (https://artemis.in.tum.de/course-management/351/quiz-exercises/14041/participations):

![participations](https://github.com/ls1intum/Artemis/assets/13812333/0d5be01d-406b-42b3-937b-626b77a95b14)

**Comment by krusche** [comment]
The logic changed: now the results are only calculated at the end date of the quiz. Is the quiz already completely over?

**Comment by krusche** [comment]
Ah just found it, not sure why the evaluation was not done at the end of the quiz. I clicked on the new "evaluate" button in the quiz details and now the results are available. Did you edit the quiz at some point?

**Comment by michael-schwarz** [comment]
Thank you for the very quick help, it's very much appreciated!

Yes, I did edit the quiz at some point after the release date (but before the first batch was started), as there was a small mistake in the questions.

We'll be sure to try whether a click on "evaluate" helps resolve the problem if we ever encounter it again before creating an issue here.

**Comment by krusche** [comment]
Great, we will investigate why the automatic evaluation did not run properly at the end of the quiz. Maybe, there is an edge case when the quiz is edited and the scheduled task is not properly re-configured in this case
