### ISSUE TITLE
`Exam mode`: The PDF summary → When the diagram is big, the next question overlaps it.

### ISSUE THREAD

**Issue by Santia-go** [ls1intum/Artemis#8930]
### Describe the bug

The PDF summary→ When the diagram is big, the next question overlaps it.

### To Reproduce

1. Solve an exam with modeling exercises
2. Create a big diagram
3. Download the summary and verify that the next question overlaps it.

### Expected behavior

The size of the diagram should be scaled to the size of the page or the next question should not overlap the diagram

### Screenshots

![image](https://github.com/ls1intum/Artemis/assets/88991954/47f26423-f226-453e-9ba5-e8412e1a0a9e)

### Which version of Artemis are you seeing the problem on?

7.3.0

### What browsers are you seeing the problem on?

Chrome

**Comment by az108** [comment]
What i was able to achieve was, increasing the modelling sumbission container so that it covers the whole exercise. Now it reaches out till the last page as seen in the images below. What I could not do was increase the card body accordingly and for some reason there is this big whitespace when the modelling card starts which i am unable to debug. I have tried emulating the print functionality and I think the root cause of issues is the fact that the sumbission container does not fit in the card body. It would be ideal to fix this somehow, help is needed 🥲
1:
<img width="715" alt="image" src="https://github.com/ls1intum/Artemis/assets/92953467/12434547-76f2-4dfe-9ccb-064248cdc7cf">
2:
<img width="715" alt="image" src="https://github.com/ls1intum/Artemis/assets/92953467/9a3ddf03-cb98-47a2-9a52-22c61e363ef4">
3:
<img width="715" alt="image" src="https://github.com/ls1intum/Artemis/assets/92953467/2cad28ba-e1db-4c89-b9eb-e6677b4bff7f">

**Comment by az108** [comment]
Update: I could aswell fix that the sumbission container adjusts its size according to the sumbission. The only problem left is the weird page break or whitespace under the card header. If the white space is gone and the modelling sumbission is displayed from the card header then everything should now fit in the sumbission container.
1.
<img width="623" alt="image" src="https://github.com/user-attachments/assets/39582fe5-0ff9-40ef-8291-9aa7c3758975">
2.
<img width="623" alt="image" src="https://github.com/user-attachments/assets/3878f5b1-a2b0-40b7-bada-b1e02328a42b">
3.
<img width="623" alt="image" src="https://github.com/user-attachments/assets/3dc7355e-9c9b-4ab5-8e7c-7c84c2e0fb11">

**Comment by az108** [comment]
The whitespace should not be there, without it the whole content will fit into the box now after the changes i have merged for the scalings of the parent containers.
The height and size of the parent containers were related to this and are fixed now and of appropriate size. This is only a edge case related to the content which gets moved by random whitespace appearing.
The whitespace does not appear for vertically normal modelling diagrams and the summary gets displayed correctly.
Emulating a print view also did not help much as fixing the error there did not fix the issue in the pdf preview.

**Comment by ge94zec** [comment]
The whitespace issue is still present and reproducible. Even though the parent container scaling and sizing have been fixed, the content still gets shifted due to unexpected whitespace

<img width="603" height="892" alt="Image" src="https://github.com/user-attachments/assets/c571dd42-1227-4101-bf69-16d2d9fa73cb" />
<img width="590" height="657" alt="Image" src="https://github.com/user-attachments/assets/64196fc8-b607-49e9-99a8-96efe44df653" />
