### ISSUE TITLE
`Exam mode:` Visible student announcements before start of exam

### ISSUE THREAD

**Issue by JohannesWt** [ls1intum/Artemis#9010]
### Describe the bug

When the instructor changes the working time for an exam the students receive a notification of this change (before the exam starts). While this is not critical for the working time, the same happens when the instructor changes the problem statement of an exercise. This announcement should not happen when the exam has not started yet.

### To Reproduce

1. Go to an (not started) exam as an instructor and change a problem statement of an exericse
2. Open the student view in parallel and receive the live announcements

### Expected behavior

It should not show any announcements of changes of the exam if it not has started yet.

### Which version of Artemis are you seeing the problem on?

7.4.1

### What browsers are you seeing the problem on?

Chrome

**Comment by lana-ati** [comment]
This was fixed in PR https://github.com/ls1intum/Artemis/pull/9102 and is therefore outdated.

**Comment by konrad2002** [comment]
This was indeed fixed but this is the corresponding pr: https://github.com/ls1intum/Artemis/pull/9136

**Comment by krusche** [comment]
Exam announcements are still shown even though they are not meaningful:
1. If the exam start was changed, but the student never opened the exam, there is no need to show the banner
2. If the duration is identical, there is no need to show (potentially duplicated) banners which are even misleading because the duration did not really change.

We should fix both issues
